theme = "custom"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
K = "goto_prev_paragraph"
J = "goto_next_paragraph"

[keys.select]
K = "goto_prev_paragraph"
J = "goto_next_paragraph"
